apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    app: webserver
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31337
    protocol: TCP
  selector:
    app: webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: httpd:alpine
        ports:
        - containerPort: 80